### PR TITLE
Improves memory efficiency

### PR DESCRIPTION
**Pull request by iuridiniz**
Relates to Issue #11

### CODE REVIEW

**Comment by iuridiniz** [comment]
Hi @sanpii,

I'm done this, I want to know if this piece of code is good enough for you. I'm very interested in your opinion about struct names and files too.

**Comment by sanpii** [comment]
Well, it’s look good for me in general. I have just some points:
- I see some TODO is the code;
- why are you using underscored type names? In rust it’s for unused variables;
- a new `String` type it’s probably a little confusing;
- your PR seems to have and empty merge commit c7d17dce8d9c5f946459a222e0c0e81ebbb455df.

**Comment by iuridiniz** [comment]
> Well, it’s look good for me in general. I have just some points:
> 
> * I see some TODO is the code;

Well, there is a same TODO for functions `unescape_bytea` `bytea`.

``` 
/* TODO: ask @sanpii, old code removes the end \0, this is not conformant with docs */
```

Here, libpq docs states that a final \0 is included in returned bytes: 

_PQescapeByteaConn returns an escaped version of the from parameter binary string in memory allocated with malloc(). This memory should be freed using PQfreemem() when the result is no longer needed. The return string has all special characters replaced so that they can be properly processed by the PostgreSQL string literal parser, and the bytea input function. **A terminating zero byte is also added**._ 

The old code strips that final '\0' and I changed them to include it. I don't know if this is ok for you. If you agree, I just will remove these TODO, if no, I will remove '\0' but that will not conform with docs.

the other TODO in Connection::error_message
```
        // TODO: make this returns a &str (c_char* -> CStr -> &str ) tied to lifetime of self
        // in order to avoid new memory allocations. We can do this since it will be freed in
        // PQfinish (when the connection is dropped).
```
It's just a reminder that this could be done in order to avoid this new String alloc. Can I proceed?

> * why are you using underscored type names? In rust it’s for unused variables;

I don't have any good names in mind. It was my fault, so I put a '_ in order to you complain. What do you thing about names `String` and `Bytes`?

> * a new `String` type it’s probably a little confusing;

Yeah, but it cannot be a std::ffi::CString, because it was not allocated by Rust. So there's another string type. It has the same purpose of std::ffi::CString (A heap allocated C String), but the memory was allocated by libpq-sys.

Also, we can merge _String and _Bytes into a single type (Bytes?). 
But I think I will have to calc the length (until the final '\0') each time that postgresql gives me a `char*` (each time that current PR returns a _String) since Bytes need a lenght. Is it ok?

If you agree, I will adjust docs in order to indicate how to convert Bytes into a rust string.

> * your PR seems to have and empty merge commit [c7d17dc](https://github.com/sanpii/libpq.rs/commit/c7d17dce8d9c5f946459a222e0c0e81ebbb455df).

I adjusted

**Comment by sanpii** [comment]
> If you agree, I just will remove these TODO, if no, I will remove '\0' but that will not conform with docs.

Yes, it’s probably a better idea to keep it.

> It's just a reminder that this could be done in order to avoid this new String alloc. Can I proceed?

Yes.

> What do you thing about names `String` and `Bytes`?

`PqBytes` and `PqString`? We easily understand who allocate there memory.

**Comment by iuridiniz** [comment]
@sanpii Done

with the exception of [40e8150 (Avoid a new allocation when using Connection::error_message)](https://github.com/sanpii/libpq.rs/pull/12/commits/40e815012be8ead98c98ce503a87ce9b96a34210), all other commits are small

**Comment by sanpii** [comment]
clippy reports many new warnings. Can you fix redundant_field_names and unnecessary_lazy_evaluations (you can ignore missing_safety_doc)?

**Comment by iuridiniz** [comment]
> clippy reports many new warnings. Can you fix redundant_field_names and unnecessary_lazy_evaluations (you can ignore missing_safety_doc)?

My bad, I didn't used clippy

**Comment by sanpii** [comment]
Merge, thank you :slightly_smiling_face:

**Pull request closed without merging**
